### ISSUE TITLE
Some links in RDoc not working

### ISSUE THREAD

**Issue by BurdetteLamar** [ruby/optparse#17]
In https://docs.ruby-lang.org/en/master/OptionParser.html#method-i-make_switch, the link to "Parameters for New Options" does not work.

I'm not sure that the files doc/*.rdoc are getting included in the RDoc, and if they are included, where the .html pages are in the output.

Do we need to add ```files.extra_rdoc_files``` to the gemspec?

**Comment by olleolleolle** [comment]
I guess that's the fix! https://guides.rubygems.org/specification-reference/#extra_rdoc_files 

Probably a `Dir[]` or a `Dir.glob` expression can do it.

**Comment by BurdetteLamar** [comment]
Will this work, do you think?

```
  spec.extra_rdoc_files = ['doc/*.rdoc']
```

**Comment by olleolleolle** [comment]
Perhaps `  spec.extra_rdoc_files = Dir.glob('doc/**/*')`

**Comment by nobu** [comment]
No, the page is generated from the ruby repository, gemspec files are irrelevant.

Because `:include:` directive inserts the content and loses the path where the content was found, relative links can’t work as in the included file directly.
This seems a bug or restriction of rdoc.

**Comment by olleolleolle** [comment]
Thanks @nobu, TIL!

**Comment by BurdetteLamar** [comment]
Thanks, @nobu and @olleolleolle.  I'll figure out how to make the links work.

**Comment by BurdetteLamar** [comment]
> 
> 
> No, the page is generated from the ruby repository, gemspec files are irrelevant.
> 
> Because `:include:` directive inserts the content and loses the path where the content was found, relative links can’t work as in the included file directly.
> This seems a bug or restriction of rdoc.

@nobu, did your recent merge fix this?  If not, I'll look into it.
