### ISSUE TITLE
Releasing version 0.1.1 to RubyGems?

### ISSUE THREAD

**Issue by joshdholtz** [ruby/optparse#27]
Hello! The README mentions that this gem be installed through RubyGems with `gem install optparse`. The latest version on RubyGems however is `0.1.0` and not `0.1.1`.

Are there plans to release `0.1.1` to RubyGems? Thanks! ❤️

**Comment by hsbt** [comment]
@joshdholtz We failed to release v0.1.1 maybe. I pushed optparse-0.1.1 now.

see https://rubygems.org/gems/optparse/versions/0.1.1

Thanks for your friendly notification.

**Comment by joshdholtz** [comment]
@hsbt Thank you thank you!! ❤️
