### ISSUE TITLE
Conflicting labels in tutorial.rdoc

### ISSUE THREAD

**Issue by nobu** [ruby/optparse#56]
There are two same labels `Defining Options`, [old one](https://github.com/ruby/optparse/pull/24/files#diff-847930dd3ac40523c1aedb290ee1acb7ef0d8b4611be6fef9cbdc70076d8c661R35) and [added at #24](https://github.com/ruby/optparse/pull/24/files#diff-847930dd3ac40523c1aedb290ee1acb7ef0d8b4611be6fef9cbdc70076d8c661R58).

**Comment by BurdetteLamar** [comment]
Proposed fixes are in open PR #57.

**Comment by hsbt** [comment]
#57 has been merged.
